### ISSUE TITLE
The arxiv version of paper?

### ISSUE THREAD

**Issue by Gatsby23** [ZikangYuan/semi_elastic_lio#1]
Would you like provide an arxiv version of the paper?

**Comment by ZikangYuan** [comment]
Thank you for your interest in our work. I just submitted arXiv 5 minutes ago, and the code will be open sourced within 48 hours

**Comment by ZikangYuan** [comment]
The code has been released.

**Comment by Gatsby23** [comment]
> The code has been released.

Nice Work, Thank you very much.

**Comment by Gatsby23** [comment]
> The code has been released.

Sorry for bothering you. But I can't find the releated work on the arxiv ?
