### ISSUE TITLE
accuracy and robust comparation

### ISSUE THREAD

**Issue by narutojxl** [ZikangYuan/semi_elastic_lio#3]
Hello doctor @ZikangYuan,
Thanks for sharing your excellent SOTA works,  semi_elastic_lio,  liw_oam and sr_lio to let us learning.  I haven't read  these articles yet. I notice in experiment of semi_elastic_lio is more accuracy than direct_lidar_inertial_odometry and liw_oam is more accuracy than sr_lio. 
My question is in the above repos,  what is the ranking order of accuracy and robust of them?  Thanks for your help in advance!

**Comment by ZikangYuan** [comment]
Thanks for your interest to our work. In terms of accuracy and robustness, **semi-elastic-lio** outperforms **direct_lidar_inertial_odometry**, and **direct_lidar_inertial_odometry** outperforms **sr-lio** on the on-board datasets. We think **sr-lio** has some issues, so we're reworking it. **liw-oam** is a framework including wheel encoding odometer observation. Therefore, comparing it with LIO systems is unfair.

**Comment by deliangye** [comment]
could you explain what difference is between elastic LIO and semi-elastic LIO? I am not clear even after reading your paper :)

**Comment by narutojxl** [comment]
Thanks author for your detailed reply !  If we ignore the fairness,  liw-oam, semi-elastic-lio and direct_lidar_inertial_odometry, which of one's accuracy and robust(e.g. in degeneration scene and wide environment) is best,  liw-oam or semi-elastic-lio?

**Comment by deliangye** [comment]
I didn't see any accuracy comparison with ct-icp from the paper, just curious how much improvement it is comparison to ct-icp?

**Comment by narutojxl** [comment]
direct_lidar_inertial_odometry is more accuracy than ct-icp in the direct_lidar_inertial_odometry's paper.

**Comment by ZikangYuan** [comment]
@deliangye 感谢您对我们工作的兴趣。CT-ICP我们也研究过相当长的一段时间。根据我们的经验，CT-ICP的求解方式其实并不好，因为ICP的点到面残差是随环境改变而改变的，而逻辑约束(当前sweep开始时的状态趋近于上一时刻结束时的状态)的权重却是设定成一个常量。这导致点到面残差和逻辑约束两者的权重关系是极其不稳定的。如果某一时刻因环境几何信息薄弱而导致点到面残差过大，逻辑约束很有可能因相对权重过低而无法严格满足。这也是我们认为CT-ICP问题的核心所在。虽然CT-ICP论文中记录在KITTI，KITTI-360和KITTI-CARLA中都能取得较好的结果。但如果在更多的测试序列(如NCLT以及厦门大学王程教授团队的自采序列)上测试就会发现，这种CT的求解方式是极其不佳的。不光耗时比传统ICP长，它的鲁棒性也是很差的。

但CT-ICP也有他自己的优势，它基于Hash体素的地图维护模式我们认为是极佳的。

之所以没有和CT-ICP比，因为我们认为CT-ICP是纯雷达系统，而我们是LIO，我们和sota比较时还是应该和LIO比。

**Comment by ZikangYuan** [comment]
@narutojxl **liw_oam** can also utilize semi-elastic module. If two systems both utilize the semi-elastic module, we think **liw_oam** is more outstanding. But we didn't make a rigorous evaluation.

**Comment by ZikangYuan** [comment]
@deliangye 您可以这么理解。首先，不论是elastic还是semi_elastic，一个sweep可以由两个时刻的状态来表达：本次sweep开始时的状态(x_begin)和结束时的状态(x_end)，逻辑约束用来使本次的x_begin无限趋近于上一时刻的x_end。

在elastic模式下，x_begin和x_end同时受CT_point_to_plane和IMU预积分约束，除此以外，x_begin还受到逻辑约束。这个缺点是x_begin会直接受到点到面残差的影响。点到面残差是随环境变化而变化的，如果点到面残差过大，逻辑约束将无法严格满足，最终导致状态求解不准。

在semi_elastic模式下，x_begin受IMU约束和逻辑约束，x_end受IMU约束和点到面残差约束。相比于点到面残差，IMU约束的大小往往取决于传感器本身的噪声，所以只要IMU预积分的时间间隔不变，IMU残差的大小往往是不会有大幅度波动的，它和逻辑约束的相对权重是很稳定的。因此，我们提出了semi_elastic的LIO求解方式。

**Comment by narutojxl** [comment]
My problem is solved, thanks again!

**Comment by deliangye** [comment]
@ZikangYuan I got it,  thanks for detail explanation!
Each point in the lidar sensor frame after initial undistortion will be fixed, and never change during the entire LIO process, although its world coordinate keeps updated with lidar pose e(i+1), right? if so, the initial undistortion is very critical step, and local map will looks a little noise due to imperfect initial undistortion. what do you think?

**Comment by ZikangYuan** [comment]
@deliangye Yes, you are right. In our system, we utilize the IMU-integrated pose to correct distortion, which is the "initial undistortion". In our experience, such distortion correction is sufficient on most publicly available datasets.

**Comment by deliangye** [comment]
@ZikangYuan curious if semi-elastic icp could produce similar result as:
https://www.bilibili.com/video/BV19m4y1E7ry/?spm_id_from=333.999.0.0&vd_source=438f630fe29bd5049b24c7f05b1bcaa3
from https://github.com/chengwei0427/ct-lio for indoor scenarios :)

**Comment by ZikangYuan** [comment]
@deliangye Maybe you can test by yourself.
