### ISSUE TITLE
What is the difference between raw_point and point

### ISSUE THREAD

**Issue by CharlieV5** [ZikangYuan/semi_elastic_lio#6]
In struct point3D, what is the difference between raw_point and point?
struct point3D {
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW

    Eigen::Vector3d raw_point;
    Eigen::Vector3d point;
    double alpha_time = 0.0;
    double relative_time = 0.0;
    double timestamp = 0.0;
    int index_frame = -1;

    point3D() = default;
};

How should I do to save all the points in world frame?

**Comment by ZikangYuan** [comment]
The *point* is the 3D coordinate in world frame with distortion correction. If you set the "motion_compensation" as *NONE* or "CONSTANT_VELOCITY", the "raw_point" is equal to "point". If you set the "motion_compensation" as *ITERATIVE* or "CONTINUOUS", the "raw_point" is the 3D coordinate directly collected from LiDAR.

**Comment by ZikangYuan** [comment]
We are sorry that we have not provide the function for saving all the points in world frame.

**Comment by CharlieV5** [comment]
Thanks!
